// Generates THIRD_PARTY_NOTICES.md and data/credits.json (the open-source list shown in "About & credits")
// from the dependencies that are actually in the project. Usage: node scripts/gen_notices.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(root, p), 'utf8');
const pkg = JSON.parse(read('package.json'));

/** Software that ships with the app (loaded by index.html / js). */
const shipped = [];
const leafletHeader = read('vendor/leaflet/leaflet.js').slice(0, 300).match(/Leaflet (\d+\.\d+\.\d+)/);
const leafletPkg = JSON.parse(read('node_modules/leaflet/package.json'));
if (!leafletHeader || leafletHeader[1] !== leafletPkg.version) throw new Error('vendor/leaflet does not match node_modules/leaflet; re-copy dist files');
if (!read('index.html').includes('vendor/leaflet/leaflet.js')) throw new Error('index.html no longer loads Leaflet');
shipped.push({
  name: 'Leaflet', version: leafletPkg.version, license: leafletPkg.license, url: 'https://leafletjs.com/',
  licenseUrl: 'https://github.com/Leaflet/Leaflet/blob/main/LICENSE', purpose: 'Map engine for the locked satellite view (vendored in vendor/leaflet).',
  licenseText: read('vendor/leaflet/LICENSE').trim(),
});

/** Development tooling: used to build and test, not distributed with the app. */
const dev = Object.keys(pkg.devDependencies || {}).filter((n) => n !== 'leaflet').map((n) => {
  const p = JSON.parse(read(`node_modules/${n}/package.json`));
  return { name: p.name, version: p.version, license: p.license, url: p.homepage || (p.repository && p.repository.url) || '' };
});
const pw = join(root, 'node_modules/playwright-core/package.json');
if (existsSync(pw) && !dev.some((d) => d.name === 'playwright-core')) {
  const p = JSON.parse(readFileSync(pw, 'utf8'));
  dev.push({ name: p.name, version: p.version, license: p.license, url: p.homepage || '' });
}

writeFileSync(join(root, 'data/credits.json'), JSON.stringify({
  generated: new Date().toISOString().slice(0, 10),
  software: shipped.map(({ licenseText, licenseUrl, ...p }) => p),
  // data used at BUILD time only (the app contacts none of them)
  data: [
    { name: 'OurAirports', license: 'public domain', url: 'https://ourairports.com/data/', purpose: 'airports, runways, countries, regions, elevation' },
    { name: 'OpenFlights', license: 'ODbL', url: 'https://github.com/jpatokal/openflights', purpose: 'route and destination counts (Practice playability score), airline names and routes (main-airline hint)' },
    { name: 'Wikidata', license: 'CC0', url: 'https://www.wikidata.org/', purpose: 'airline-hub relations (main-airline hint; the curated main airline of the 100 Major hubs, data/hub_airlines.json), Wikipedia article titles, passenger counts P3872 (Major hubs 51-100, mixed years 2019-2025), language-edition counts (playability score)' },
    { name: 'Wikipedia', license: 'CC BY-SA 4.0 (facts only, no text copied); link target in the app', url: 'https://www.wikipedia.org/', purpose: 'article link on the result card; at build time the current article of each Major hub was read to curate its main airline (airline names and source URLs only)' },
  ],
}, null, 2) + '\n');

const md = `# Third-party notices

Generated by \`scripts/gen_notices.mjs\` from the dependencies actually present in this repository. Airport Guesser itself
is by Kevin Pahud.

## Software shipped with the app

${shipped.map((p) => `### ${p.name} ${p.version}\n\n- Licence: ${p.license} (${p.licenseUrl})\n- Project: ${p.url}\n- Use: ${p.purpose}\n\n\`\`\`\n${p.licenseText}\n\`\`\`\n`).join('\n')}
No framework, no bundler and no fonts are shipped: the app is plain JavaScript, HTML and CSS using the system font stack.

## Development tooling (not distributed with the app)

${dev.map((d) => `- ${d.name} ${d.version}, ${d.license}${d.url ? ` (${d.url})` : ''}`).join('\n')}

Used only for the test scripts and to generate icons.

## Data and services

- **Esri World Imagery** (map tiles; the build also queries the tile availability service). Used under Esri's terms, with the required attribution shown on every image. https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9
- **OurAirports** airport, runway and country data (airports.csv, runways.csv, countries.csv). Public domain. https://ourairports.com/data/
- **Wikidata** (CC0 1.0) and the **MediaWiki API**, used only at build time to verify and look up Wikipedia article titles (scripts/wikipedia_links.py) to read airline-hub relations for the third hint (scripts/hint_data.py) and, with each Major hub's current Wikipedia article, to curate the main airline of the 100 Major hubs (data/hub_airlines.json, scripts/hub_evidence.py: airline names and source URLs only, no article text is copied), and passenger counts (P3872, mixed years 2019-2025) and language-edition counts for the Practice tiers (scripts/practice_tiers.mjs). The app stores article titles only and links to wikipedia.org; Wikipedia text is not copied. https://www.wikidata.org/
- **OpenFlights** route data (routes.dat) and airline records (airlines.dat), used only at build time for the Practice playability score (route and destination counts) and to choose an airport's main airline for the third hint. Open Database Licence (ODbL). https://github.com/jpatokal/openflights

## Disclaimer

Not affiliated with or endorsed by any airport, airline, or data and imagery provider. Imagery may be outdated.
`;
writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), md);
console.log('wrote THIRD_PARTY_NOTICES.md and data/credits.json:', shipped.map((p) => `${p.name} ${p.version} (${p.license})`).join(', '));
