// Generates THIRD_PARTY_NOTICES.md and data/credits.json (the open-source list shown in "About & credits")
// from the dependencies that are actually in the project. Usage: node scripts/gen_notices.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(root, p), 'utf8');
const pkg = JSON.parse(read('package.json'));

/** Software that ships with the app (loaded by index.html / js). */
const shipped = [];
const leafletHeader = read('vendor/leaflet/leaflet.js').slice(0, 300).match(/Leaflet (\d+\.\d+\.\d+)/);
const leafletPkg = JSON.parse(read('node_modules/leaflet/package.json'));
if (!leafletHeader || leafletHeader[1] !== leafletPkg.version) throw new Error('vendor/leaflet does not match node_modules/leaflet; re-copy dist files');
if (!read('index.html').includes('vendor/leaflet/leaflet.js')) throw new Error('index.html no longer loads Leaflet');
shipped.push({
  name: 'Leaflet', version: leafletPkg.version, license: leafletPkg.license, url: 'https://leafletjs.com/',
  licenseUrl: 'https://github.com/Leaflet/Leaflet/blob/main/LICENSE', purpose: 'Map engine for the locked satellite view (vendored in vendor/leaflet).',
  licenseText: read('vendor/leaflet/LICENSE').trim(),
});

/** Development tooling: used to build and test, not distributed with the app. */
const dev = Object.keys(pkg.devDependencies || {}).filter((n) => n !== 'leaflet').map((n) => {
  const p = JSON.parse(read(`node_modules/${n}/package.json`));
  return { name: p.name, version: p.version, license: p.license, url: p.homepage || (p.repository && p.repository.url) || '' };
});
const pw = join(root, 'node_modules/playwright-core/package.json');
if (existsSync(pw) && !dev.some((d) => d.name === 'playwright-core')) {
  const p = JSON.parse(readFileSync(pw, 'utf8'));
  dev.push({ name: p.name, version: p.version, license: p.license, url: p.homepage || '' });
}

writeFileSync(join(root, 'data/credits.json'), JSON.stringify({
  generated: new Date().toISOString().slice(0, 10),
  software: shipped.map(({ licenseText, licenseUrl, ...p }) => p),
}, null, 2) + '\n');

const md = `# Third-party notices

Generated by \`scripts/gen_notices.mjs\` from the dependencies actually present in this repository. Airport Guesser itself
is by Kevin Pahud.

## Software shipped with the app

${shipped.map((p) => `### ${p.name} ${p.version}\n\n- Licence: ${p.license} (${p.licenseUrl})\n- Project: ${p.url}\n- Use: ${p.purpose}\n\n\`\`\`\n${p.licenseText}\n\`\`\`\n`).join('\n')}
No framework, no bundler and no fonts are shipped: the app is plain JavaScript, HTML and CSS using the system font stack.

## Development tooling (not distributed with the app)

${dev.map((d) => `- ${d.name} ${d.version}, ${d.license}${d.url ? ` (${d.url})` : ''}`).join('\n')}

Used only for the test scripts and to generate icons.

## Data and services

- **Esri World Imagery** (map tiles; the build also queries the tile availability service). Used under Esri's terms, with the required attribution shown on every image. https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9
- **OurAirports** airport, runway and country data (airports.csv, runways.csv, countries.csv). Public domain. https://ourairports.com/data/
- **OpenFlights** route data (routes.dat), used only at build time to order the Practice "Top 100" set. Open Database Licence (ODbL). https://github.com/jpatokal/openflights

## Disclaimer

Not affiliated with or endorsed by any airport, airline, or data and imagery provider. Imagery may be outdated.
`;
writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), md);
console.log('wrote THIRD_PARTY_NOTICES.md and data/credits.json:', shipped.map((p) => `${p.name} ${p.version} (${p.license})`).join(', '));
